# Generated by Django 4.1.1 on 2022-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='age_restriction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='imdb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='year_movie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
