# Generated by Django 4.1.1 on 2022-11-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_show_age_restriction_show_imdb_show_year_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Serial',
        ),
    ]
