# Generated by Django 4.1.1 on 2022-11-12 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_serials_delete_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imdb', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('Best Of International Shows', 'Best Of International Shows'), ('Popular Shows', 'Popular Shows')], max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('year_show', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=200)),
                ('main_image', models.ImageField(blank=True, upload_to='main_photo/')),
                ('image', models.ImageField(upload_to='photos/')),
                ('video', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Serials',
        ),
    ]
