# Generated by Django 4.1.1 on 2022-11-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_season_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image_episode',
            field=models.ImageField(default=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
