# Generated by Django 4.1.1 on 2022-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_episode_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
