# Generated by Django 4.1.1 on 2022-11-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_alter_episode_season_delete_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
