# Generated by Django 4.1.1 on 2022-11-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_episode_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='image_episode',
            new_name='thumbnail',
        ),
    ]
