# Generated by Django 4.1.1 on 2022-11-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_rename_image_episode_episode_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
