# Generated by Django 4.1.1 on 2022-11-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_season_alter_episode_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
