# Generated by Django 4.1.1 on 2022-11-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0040_alter_season_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='video',
            new_name='video_trailer',
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
