# Generated by Django 4.1.1 on 2022-11-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0041_rename_video_show_video_trailer_alter_episode_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_no', models.IntegerField()),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.show')),
            ],
        ),
    ]
