# Generated by Django 4.1.1 on 2022-11-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0045_episode_season_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series'),
        ),
    ]
