# Generated by Django 4.1.1 on 2022-11-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0046_alter_episode_season_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='season_no',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
