# Generated by Django 4.1.1 on 2022-11-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0047_remove_episode_season_no_delete_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.CharField(choices=[('Best Of International Shows', 'Best Of International Shows'), ('Popular Shows', 'Popular Shows'), ('Familiar TV Favorites', 'Familiar TV Favorites')], max_length=100),
        ),
    ]
