# Generated by Django 4.1.1 on 2022-11-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0048_alter_show_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.CharField(default=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
