# Generated by Django 4.1.1 on 2022-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0049_alter_episode_video_alter_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action & Adventure', 'Action & Adventure'), ('Comedies', 'Comedies'), ('Drama', 'Drama'), ('Blockbuster Movies', 'Blockbuster Movies'), ('Popular Movies', 'Popular Movies'), ('Documentaries', 'Documentaries')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Documentary Films', 'Documentary Films'), ('Watch In One Night', 'Watch In One Night'), ('Exciting Movies', 'Exciting Movies'), ('Critically Acclaimed Films', 'Critically Acclaimed Films'), ('Familiar Favorites', 'Familiar Favorites')], max_length=50),
        ),
    ]
