# Generated by Django 4.1.1 on 2022-11-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0050_alter_movie_category_alter_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action & Adventure', 'Action & Adventure'), ('Comedies', 'Comedies'), ('Drama', 'Drama'), ('Blockbuster Movies', 'Blockbuster Movies'), ('Popular Movies', 'Popular Movies'), ('Cartoons', 'Cartoons')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Animal Tales', 'Animal Tales'), ('Watch In One Night', 'Watch In One Night'), ('Exciting Movies', 'Exciting Movies'), ('Critically Acclaimed Films', 'Critically Acclaimed Films'), ('Familiar Favorites', 'Familiar Favorites')], max_length=50),
        ),
    ]
