# Generated by Django 4.1.1 on 2022-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0052_remove_movie_episode_number_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.CharField(choices=[('Exciting Movies', 'Exciting Movies'), ('Critically Acclaimed Films', 'Critically Acclaimed Films'), ('Familiar Favorites', 'Familiar Favorites'), ('Documentary Films', 'Documentary Films')], max_length=50),
        ),
    ]
