# Generated by Django 4.1.1 on 2022-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0053_alter_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.CharField(choices=[('Exciting Movies', 'Exciting Movies'), ('Critically Acclaimed Films', 'Critically Acclaimed Films'), ('Familiar Favorites', 'Familiar Favorites'), ('Documentary Films', 'Documentary Films'), ('Popular Documentaries', 'Popular Documentaries')], max_length=50),
        ),
    ]
